import {freshState,amount,slotOptions,fixtures,edit,approve,assertApproved,verifyCapture,audit,canEdit} from '../src/domain.mjs';
import {database,load,save,reserve,release} from '../src/db.mjs';
import {paypalReady,paypal,createPayPalOrder,verifyWebhook} from '../src/paypal.mjs';
import {draftRequest} from '../src/ai.mjs';
import {assets} from '../src/assets.mjs';
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
const security={'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Permissions-Policy':'camera=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self' https://chatgpt.com"};
async function session(request,db){let id=request.headers.get('cookie')?.match(/(?:^|; )fieldnote=([a-f0-9-]{36})(?:;|$)/)?.[1];let state=id?await load(db,id):null;let cookie;if(!state){id=crypto.randomUUID();state=freshState();await db.run('INSERT INTO sessions(id,state,revision,updated) VALUES(?,?,?,?)',id,JSON.stringify(state),state.version,Date.now());cookie=`fieldnote=${id}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800${new URL(request.url).protocol==='https:'?'; Secure':''}`;}return {id,state,cookie};}
async function view(db,id,state,env){const rows=await db.all('SELECT slot,session,state,expires FROM slots WHERE expires>?',Date.now());return {state,mode:paypalReady(env)?'sandbox':'demo',ai:env.OPENAI_API_KEY&&env.AI_MODE==='openai'?'OpenAI extraction':'Rules-based demo',currency:'USD',timezone:'UTC',availability:slotOptions().map(slot=>({slot,status:fixtures().includes(slot)?'busy':rows.find(r=>r.slot===slot)?.session===id&&(rows.find(r=>r.slot===slot)?.state==='held'||state.stage==='booked'&&state.slot===slot)?'yours':rows.some(r=>r.slot===slot)?'busy':'available'}))};}
async function complete(db,id,state,orderId,providerOrder,mode,eventId,attempt=0){
const record=await db.one('SELECT * FROM orders WHERE id=? AND session=?',orderId,id);
if(!record||record.status==='cancelled'||record.mode!==mode)throw Error('This payment is no longer associated with the current request.');
const capture=verifyCapture(providerOrder,{id:orderId,amount:record.amount,session:id});
if(state.stage==='booked'&&state.order?.id===orderId&&state.payment?.capture===capture)return {state,duplicate:true};
assertApproved(state);
if(state.order?.id!==orderId||state.approval.fingerprint!==state.order.fingerprint)throw Error('Payment needs manual reconciliation because the request changed.');
const lock=await db.one('SELECT * FROM slots WHERE slot=?',state.slot);
if(lock?.session!==id)throw Error('Payment verified, but the scheduling lock needs manual reconciliation.');
const next=audit({...state,version:state.version+1,stage:'booked',payment:{status:mode==='demo'?'DEMO_COMPLETED':'SANDBOX_COMPLETED',capture,amount:record.amount,at:new Date().toISOString(),mode}},mode==='demo'?'Demo payment fixture verified; simulated booking reserved.':'PayPal sandbox capture verified; sandbox booking reserved.');
const encoded=JSON.stringify(next);const gate="EXISTS (SELECT 1 FROM sessions WHERE id=? AND revision=? AND state=?)";
const result=await db.batch([
["UPDATE sessions SET state=?,revision=?,updated=? WHERE id=? AND revision=? AND EXISTS (SELECT 1 FROM slots WHERE slot=? AND session=?) AND EXISTS (SELECT 1 FROM orders WHERE id=? AND status!='cancelled')",encoded,next.version,Date.now(),id,state.version,state.slot,id,orderId],
["UPDATE orders SET status='completed',capture=? WHERE id=? AND "+gate,capture,orderId,id,next.version,encoded],
["UPDATE slots SET state='booked',expires=? WHERE slot=? AND session=? AND "+gate,8640000000000000,state.slot,id,id,next.version,encoded],
["INSERT INTO events(id,order_id,created) SELECT ?,?,? WHERE "+gate+" ON CONFLICT(id) DO NOTHING",eventId,orderId,Date.now(),id,next.version,encoded]
]);
const current=await load(db,id);
if(result[0].meta.changes===1)return {state:current,duplicate:false};
if(current.stage==='booked'&&current.order?.id===orderId&&current.payment?.capture===capture)return {state:current,duplicate:true};
if(attempt<3&&current.version!==state.version&&current.order?.id===orderId)return complete(db,id,current,orderId,providerOrder,mode,eventId,attempt+1);
throw Error('Payment was verified but the request changed. Reconcile again; no duplicate payment will be made.');
}
async function webhook(request,env,db){if(!paypalReady(env))return json({error:'Sandbox webhooks are disabled in demo mode.'},503);const event=await request.json();await verifyWebhook(env,request.headers,event);if(!event.id)throw Error('Missing webhook event ID.');if(await db.one('SELECT id FROM events WHERE id=?',event.id))return json({ok:true,duplicate:true});if(event.event_type!=='PAYMENT.CAPTURE.COMPLETED')return json({ok:true,ignored:true});const orderId=event.resource?.supplementary_data?.related_ids?.order_id;const record=await db.one('SELECT * FROM orders WHERE id=?',orderId||'');if(!record)return json({ok:true,ignored:true});const providerOrder=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(orderId));const state=await load(db,record.session);const result=await complete(db,record.session,state,orderId,providerOrder,'sandbox',event.id);return json({ok:true,duplicate:result.duplicate});}
export default {async fetch(request,env){const url=new URL(request.url);try{if(!url.pathname.startsWith('/api/')){const key=url.pathname==='/'?'/index.html':url.pathname;const asset=assets[key];if(!asset)return new Response('Not found',{status:404});return new Response(asset.body,{headers:{'Content-Type':asset.type,...security}});}const db=database(env);if(url.pathname==='/api/paypal/webhook'&&request.method==='POST')return await webhook(request,env,db);const ctx=await session(request,db);let {id,state}=ctx;const output=async(extra={})=>json({...await view(db,id,state,env),...extra},200,ctx.cookie?{'Set-Cookie':ctx.cookie}:{});if(url.pathname==='/api/state'&&request.method==='GET')return output();if(request.method!=='POST')return json({error:'Method not allowed'},405);if(request.headers.get('origin')!==url.origin)return json({error:'Same-origin request required'},403);if(!request.headers.get('content-type')?.includes('application/json'))return json({error:'JSON required'},415);const raw=await request.text();if(raw.length>15000)return json({error:'Request is too large'},413);const body=JSON.parse(raw);if(body.version!==state.version)return json({error:'This request changed. Refresh the latest version before continuing.'},409);const mode=paypalReady(env)?'sandbox':'demo';
if(url.pathname==='/api/draft'){canEdit(state);const draft=await draftRequest(env,body.request,body.details||{});const next=audit(edit(state,{...draft,slot:state.slot}),'Draft scope and catalog prices prepared for review.');state=await save(db,id,state,next);await release(db,id);return output();}
if(url.pathname==='/api/edit'){canEdit(state);const next=audit(edit(state,{lines:body.lines,slot:body.slot}),'Quote or time changed; previous approval revoked.');state=await save(db,id,state,next);await release(db,id);return output();}
if(url.pathname==='/api/approve'){canEdit(state);const next=audit(approve(state,body.version),'Exact scope, price, and slot approved.');await reserve(db,id,next.slot);try{state=await save(db,id,state,next);}catch(e){await release(db,id);throw e;}return output();}
if(url.pathname==='/api/order'){assertApproved(state);if(state.stage==='creating'&&state.attemptMode&&state.attemptMode!==mode)throw Error('Payment mode changed. Restore the original adapter to continue safely.');if(state.order&&state.stage==='awaiting')return output();if(!['approved','creating'].includes(state.stage))throw Error('Review and approve the quote before creating a payment.');await reserve(db,id,state.slot);if(state.stage==='approved'){const next={...state,version:state.version+1,stage:'creating',attemptMode:mode,requestKey:'create-'+crypto.randomUUID()};state=await save(db,id,state,next);}try{let orderId,approvalUrl;if(mode==='sandbox'){const p=await createPayPalOrder(env,state,url.origin,id);orderId=p.id;approvalUrl=p.links?.find(l=>l.rel==='payer-action'||l.rel==='approve')?.href;if(!orderId||!approvalUrl)throw Error('PayPal did not return an approval link.');if(new URL(approvalUrl).hostname!=='www.sandbox.paypal.com')throw Error('Unexpected PayPal sandbox approval destination.');}else orderId='DEMO-'+crypto.randomUUID();await db.run('INSERT INTO orders(id,session,revision,amount,status,mode) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING',orderId,id,state.version,amount(state.lines),'created',mode);const persisted=await db.one('SELECT * FROM orders WHERE id=?',orderId);if(persisted.session!==id||persisted.amount!==amount(state.lines)||persisted.mode!==mode)throw Error('Order integrity check failed.');state=await save(db,id,state,audit({...state,version:state.version+1,stage:'awaiting',order:{id:orderId,approvalUrl,mode,fingerprint:state.approval.fingerprint}},mode==='demo'?'Demo order created. No payment provider was contacted.':'PayPal sandbox order created. Waiting for buyer approval.'));return output();}catch(e){state=await save(db,id,state,audit({...state,version:state.version+1,stage:'creating'},'Order setup is uncertain. Retry with the same idempotency key.'));throw e;}}
if(url.pathname==='/api/capture'){assertApproved(state);if(state.order?.mode!==mode)throw Error('Payment mode changed. Restore the original adapter to reconcile this order.');if(state.stage==='booked')return output({notice:'Already processed. The booking was not duplicated.'});if(!state.order||!['awaiting','capturing','reconciling'].includes(state.stage))throw Error('Create a payment order first.');const lock=await db.one('SELECT * FROM slots WHERE slot=?',state.slot);if(lock?.session!==id||lock.expires<Date.now())throw Error('Your slot hold expired. Cancel this checkout and select a new slot.');if(mode==='demo'&&body.outcome==='declined'){state=await save(db,id,state,audit({...state,version:state.version+1},'Demo payment declined. No booking was made.'));return output({notice:'Demo payment declined. Try another outcome or cancel checkout.'});}if(mode==='demo'&&body.outcome==='pending'){state=await save(db,id,state,audit({...state,version:state.version+1},'Demo payment pending. Booking remains unconfirmed.'));return output({notice:'Demo payment is pending. A pending payment never confirms a booking.'});}const reconcile=state.stage==='reconciling'||state.stage==='capturing';state=await save(db,id,state,{...state,version:state.version+1,stage:'capturing'});await db.run("UPDATE slots SET expires=? WHERE slot=? AND session=?",8640000000000000,state.slot,id);try{let provider;if(mode==='demo'){provider={id:state.order.id,status:'COMPLETED',purchase_units:[{custom_id:id,payments:{captures:[{id:'DEMO-CAP-'+state.order.id,status:'COMPLETED',amount:{currency_code:'USD',value:(amount(state.lines)/100).toFixed(2)}}]}}]};}else{if(reconcile){provider=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(state.order.id));if(provider.status==='APPROVED')provider=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(state.order.id)+'/capture','POST',{},'capture-'+state.order.id);}else provider=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(state.order.id)+'/capture','POST',{},'capture-'+state.order.id);}const done=await complete(db,id,state,state.order.id,provider,mode,'capture-'+state.order.id);state=done.state;return output({notice:mode==='demo'?'Demo only: the simulated payment was verified and the slot is reserved.':'Sandbox payment verified. Booking confirmed in the sandbox.'});}catch(e){const current=await load(db,id);if(current.stage!=='booked')state=await save(db,id,current,audit({...current,version:current.version+1,stage:'reconciling'},'Payment is unverified. Keep the slot locked until reconciliation.'));throw e;}}
if(url.pathname==='/api/replay'){if(mode!=='demo'||state.stage!=='booked')throw Error('Complete a demo booking before replaying its event.');const count=await db.one('SELECT COUNT(*) AS count FROM events WHERE order_id=?',state.order.id);return output({notice:'Duplicate event ignored. Still 1 booking and '+count.count+' processed payment event.'});}
if(url.pathname==='/api/cancel'){if(['creating','capturing','reconciling'].includes(state.stage))throw Error('Payment status is uncertain. Reconcile it before cancellation.');if(state.stage==='booked'&&state.payment?.mode!=='demo')throw Error('A captured sandbox booking needs a refund workflow before cancellation.');const oldOrder=state.order;const cancelCurrentBooked=state.stage==='booked'&&state.payment?.mode==='demo';state=await save(db,id,state,audit({...state,version:state.version+1,stage:'review',approval:null,order:null,payment:null},'Checkout cancelled; slot released.'));if(oldOrder)await db.run("UPDATE orders SET status='cancelled' WHERE id=?",oldOrder.id);await db.run("DELETE FROM slots WHERE session=? AND slot=? AND (state='held' OR ?=1)",id,state.slot,cancelCurrentBooked?1:0);return output({notice:'Cancelled. The slot is available again.'});}
if(url.pathname==='/api/reset'){if(['creating','capturing','reconciling'].includes(state.stage))throw Error('Reconcile the current payment before starting a new request.');if(state.stage!=='booked')await release(db,id);const next=freshState();next.version=state.version+1;state=await save(db,id,state,next);return output({notice:'New request ready. Any previous confirmed booking stays reserved.'});}
return json({error:'Not found'},404);
}catch(error){console.error('Fieldnote request failed:',error.message);return json({error:error.message||'Unable to complete that step. Please try again.'},400);}}};
