import {assertApproved,amount} from "./domain.mjs";
// Sandbox only. Secrets never leave the Worker. A live endpoint is intentionally unsupported.
const PAYPAL='https://api-m.sandbox.paypal.com';
export function paypalReady(env){return env.PAYPAL_MODE==='sandbox'&&!!env.PAYPAL_CLIENT_ID&&!!env.PAYPAL_CLIENT_SECRET;}
async function token(env){if(!paypalReady(env))throw Error('PayPal sandbox is not configured.');const r=await fetch(PAYPAL+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+btoa(env.PAYPAL_CLIENT_ID+':'+env.PAYPAL_CLIENT_SECRET),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('PayPal sandbox authentication failed.');return (await r.json()).access_token;}
export async function paypal(env,path,method='GET',body,requestId){const t=await token(env);const r=await fetch(PAYPAL+path,{method,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...(requestId?{'PayPal-Request-Id':requestId}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error('PayPal sandbox request failed ('+r.status+'). Reconcile the payment before trying again.');return data;}
export async function createPayPalOrder(env,state,origin,session){assertApproved(state);return paypal(env,'/v2/checkout/orders','POST',{intent:'CAPTURE',purchase_units:[{custom_id:session,description:'Fieldnote service quote',amount:{currency_code:'USD',value:(amount(state.lines)/100).toFixed(2)}}],payment_source:{paypal:{experience_context:{user_action:'PAY_NOW',shipping_preference:'NO_SHIPPING',return_url:origin+'/app?paypal=return',cancel_url:origin+'/app?paypal=cancel'}}}},state.requestKey);}
export function validateWebhookEnvelope(headers,event){
 for(const name of ['paypal-auth-algo','paypal-cert-url','paypal-transmission-id','paypal-transmission-sig','paypal-transmission-time']){const value=headers.get(name);if(!value||value.length>4096||/[\r\n]/.test(value))throw Error('Missing or invalid PayPal signature headers.');}
 const certificate=new URL(headers.get('paypal-cert-url'));if(certificate.protocol!=='https:'||certificate.hostname!=='api.sandbox.paypal.com'||certificate.username||certificate.password||!certificate.pathname.startsWith('/v1/notifications/certs/'))throw Error('Unexpected sandbox webhook certificate.');
 if(!Number.isFinite(Date.parse(headers.get('paypal-transmission-time')))||!event||typeof event!=='object'||Array.isArray(event)||typeof event.id!=='string'||event.id.length>150||typeof event.event_type!=='string'||!event.resource||typeof event.resource!=='object')throw Error('Invalid PayPal webhook envelope.');
}
export async function verifyWebhook(env,headers,event){if(!env.PAYPAL_WEBHOOK_ID)throw Error('Webhook verification is not configured.');validateWebhookEnvelope(headers,event);const result=await paypal(env,'/v1/notifications/verify-webhook-signature','POST',{auth_algo:headers.get('paypal-auth-algo'),cert_url:headers.get('paypal-cert-url'),transmission_id:headers.get('paypal-transmission-id'),transmission_sig:headers.get('paypal-transmission-sig'),transmission_time:headers.get('paypal-transmission-time'),webhook_id:env.PAYPAL_WEBHOOK_ID,webhook_event:event});if(result.verification_status!=='SUCCESS')throw Error('Invalid webhook signature.');return true;}
